### PR TITLE
Initial merging of dcos and standard scale images

### PR DESCRIPTION
**Pull request by tclarke**

### CODE REVIEW

**Comment by dfaller** [comment]
I would like to have Dan take a look at this.

**Comment by droessne** [comment]
Almost everything looks good except the changing of the UI in the scale.conf file. this is needed for proper dcos proxy redirection. Also why are you removing the DCOS scale DB directory? This is needed if the user is not using a pre-built database.

**Comment by tclarke** [comment]
@droessne It has to be rooted at /ui/ ? Can't we handle that in the haproxy config so apache see's / and haproxy rewrites from /ui/ to /? The ui is going to incorrect for most other deployments so our other option is to template the conf file or possibly use a variable (I'd have to look into apache variables to make sure they can be used in a Location)

As for the db, are you referring to the scale db image? It should be using the mdillon/postgis image from the docker hub now instead of requiring a custom image.

**Comment by droessne** [comment]
The proxy is not configurable it is built into DCOS.

The DB is fine then i just wanted to make sure we had something.

**Comment by tclarke** [comment]
ok, I'll make a change to fix the ui prefix issue

**Comment by dickmancj-mil** [comment]
LGTM

**Pull request merged**
