### PR TITLE
CSS Tweaks

### PR DESCRIPTION
**Pull request by bowmanmc**
Get rid of blue tint on page background and underlined text in nav logo

### CODE REVIEW

**Comment by dfaller** [comment]
Can you add a screenshot please for UI issues?

**Comment by bowmanmc** [comment]
screen shot 2017-02-06 at 4 03 33 pm

**Comment by bowmanmc** [comment]
Favicon changes
screen shot 2017-02-07 at 8 31 19 am

**Comment by bowmanmc** [comment]
screen shot 2017-02-07 at 8 57 41 am

**Pull request merged**
