### PR TITLE
Static Demo

### PR DESCRIPTION
**Pull request by ericsvendsen-mil**
This contains all the changes made for the static demo site, including mocks, stubs, and UI layout and behavior fixes and enhancements.  I tested this branch on site and everything looks good.  The only thing I didn't do was actually create a recipe, so somebody may want to do that.  However I ensured that existing recipes did validate properly.  Some highlights:

* Altered the layout and css of the navigation and content columns to produce more consistent results
* Modified the master/detail layout (used on recipe types and job types) to make sure content doesn't scroll beyond the current viewport height
* Many fixes to the recipe editor regarding adding inputs/outputs, editing input file and trigger information, and layout/rendering fixes.
* Mocked virtually all data and stubbed out most (if not all) API calls to enable users to create/save recipes, view interactive metrics data, and provide real-world examples of job types and recipes.
* Includes a fix for issue #29

### CODE REVIEW

**Comment by wardcr** [comment]
I did a run through of many of the screens. Here are some things I found:
- Remove "Scale" text from the version string at the bottom of the nav bar.
- Job Types and Recipe Types pages, there seems to be a gap (around 1in on my screen) at the bottom. It would be nice if the white panel used all the available space like say the Jobs page.
- Recipes Page: Pager layout is broken and showing on top of the table.
- If I click on a table row on the load/running page it doesn't seem to take me to the right filtered results, but maybe you just didn't get to that yet.
- Clicking on a table row on the load/queued page should probably go somewhere for consistency.

**Comment by ericsvendsen-mil** [comment]
Thanks for looking through this @wardcr.  I fixed the first 3 things you mentioned.  Filtering grid results is indeed something I haven't gotten to yet.  The click-through on a grid row on the load/queued page is something I talked about with Derick earlier this week, and I'll probably just create a separate issue for that.

Let me know if anything else catches your attention with this branch.

**Comment by wardcr** [comment]
On the recipes page, hovering over a table row does not show the blue background for cells in the completed column that don't have a value. I know you were going to take another pass on styling that anyway though.

I think we should get this merged at this point since it's a big one and then move on to the next items.

**Comment by ericsvendsen-mil** [comment]
Agreed.  I'll make a note of the recipes grid styling and merge this in.

**Pull request merged**
