### PR TITLE
Issue #232 - Error Color and Text of Master and Scheduler Status on Overview

### PR DESCRIPTION
**Pull request by ericsvendsen-mil**
I decided to go with a gray status color when the cluster status is unreachable since that conveys that the status is unknown.  Screenshot attached. 
image

### CODE REVIEW

**Comment by wardcr** [comment]
I'm okay with the UI appearance, but I'm curious if there are actual concrete cases where the cluster is unreachable and that *isn't* a problem? If there is, then this is fine, but if not then it should probably be represented as an error from an admin's point of view.

**Comment by ericsvendsen-mil** [comment]
From my point of view, an unreachable cluster could be a result of localized network problems or other things completely unrelated to the system itself, therefore there's no way of knowing whether an actual error occurred or not.  I was just trying to differentiate when an actual error happened that can be reported vs. an unknown.

Whatever makes the most sense is fine with me though - my understanding of this case is admittedly vague.

**Comment by wardcr** [comment]
I would suggest then if you aren't aware of something specific, from an admin's point of view any type of network problem is still something they want to investigate and draw attention to. You can still leave the sub-text as is to indicate that the machine is unreachable rather than a more specific error.

**Comment by ericsvendsen-mil** [comment]
image

**Pull request merged**
