### PR TITLE
minor updates

### PR DESCRIPTION
**Pull request by ericsvendsen-mil**
corrected workspace broker fields; bugfix for node page height

### CODE REVIEW

**Comment by tclarke** [comment]
LGTM pending travis checks

**Comment by dfaller** [comment]
It looks like you replaced "nfs_path" with "mount" in the nfs broker. The field really is "nfs_path".

"host_path" is correct for the host broker.

**Comment by ericsvendsen-mil** [comment]
I changed these based off what was being returned by the API this morning.  After testing on-site everything worked.  I can change "mount" back to "nfs_path" if that is indeed what the api will come back with though.

**Comment by dfaller** [comment]
nfs_path is indeed correct for the nfs broker.

I think what you saw was an outdated config in a legacy workspace in dev. I will correct it to prevent future confusion.

**Comment by ericsvendsen-mil** [comment]
Makes sense, thanks for catching that.

**Comment by dfaller** [comment]
LGTM now

**Pull request merged**
