### PR TITLE
Issue 182 - Fix Error Category Colors on Overview

### PR DESCRIPTION
**Pull request by ericsvendsen-mil**

### CODE REVIEW

**Comment by wardcr** [comment]
Okay, after seeing this in person, I think the approach can work. It definitely seems easier to read and clearer compared to the old version. I would suggest a couple tweaks:

- The order of the errors and the gradient should be fixed. So the tool-tip should always show System, Data, Algorithm from left to right (like the health meter) and the gradient should also follow that from bottom to top (since that matches typical lighting used in icons). That should reinforce the legend and make things feel more consistent across the grid cells.

- We might want to consider using a similar gradient effect for running vs. completed jobs for consistency? At a minimum I think we should add running count on the same line as completed to reinforce what the count means that's displayed in the cell. So if we do that it, it would probably look nicer if it was styled the same way the errors are.

**Comment by ericsvendsen-mil** [comment]
Sorted errors into System > Data > Algorithm order, and added running count to the tooltip.  I don't think adding a gradient for running vs. completed is necessary - the tooltip is enough to get that across.

**Comment by wardcr** [comment]
LGTM.

**Comment by ericsvendsen-mil** [comment]
Showed this to JP and he brought up some questions. Can possibly be reviewed during the next sprint meeting.

**Comment by ericsvendsen-mil** [comment]
Job types with running jobs now have a background animation; changed data errors to orange as JP suggested; reordered error categories to reflect their severity.

**Comment by wardcr** [comment]
I think the orange is probably okay.

I still have concerns that the pulsing may make the dashboard harder to interpret when you have so many things changing on the screen at once, compared to the single cell on the data feed page. We can try it for a bit and see how others feel. One other idea I had was maybe using a single spinner somewhere towards the top of the grid cells with the total number of running jobs so that you still get a feel for something happening, but in a form that's a bit less overwhelming.

**Comment by ericsvendsen-mil** [comment]
I'm going to merge this but leave issue #182 open so we can make a decision later based on feedback from others.

**Pull request merged**
