### PR TITLE
WIP: Provide an alternate AWS Endpoint URL for testing

### PR DESCRIPTION
**Pull request by jeremysnyder**

### CODE REVIEW

**Comment by JohnPTobe** [comment]
Sorry, I assumed it was possible and just copied the first google link I found.  I take this is for running a test environment? Or just for running unit tests?

**Comment by JohnPTobe** [comment]
We'll take a look at this when it's ready but I suspect it could be better accomplished via aws config settings (which boto uses) or an environment variable.

**Comment by emimaesmith** [comment]
As it's been over a month with no activity, I'm going to close this PR.

**Comment by jeremysnyder** [comment]
Yeah, sorry about that.  I have been wanting to get back to this, but haven't had the time.  If I get back to it again and have coverage for my work, I will reopen a PR.

**Pull request closed without merging**
