### PR TITLE
Add Functionality to Include docker_params

### PR DESCRIPTION
**Pull request by steph2a1**
Two files were edited to allow for docker_params to be added

### CODE REVIEW

**Comment by dfaller** [comment]
There appears to be a travis build issue with your PR. We're looking at it.

**Comment by gisjedi** [comment]
The underlying issue was related to pull request against master. This is commonly the branch external developers will be making requests against, so the issue has been fixed. I told believe I'm able to correct this without a rebase of the remote repo. I'm closing this PR and will open a new one see if that will apply the updates I've made in master to the build.

**Comment by dfaller** [comment]
The current pull request out there has conflicts with the master branch that will need to be resolved. We haven't reviewed your recent changes yet, we need the conflict resolved first.

**Comment by antman1p** [comment]
Oh, ok.  What needs to happen to resolve the conflict?

**Comment by dfaller** [comment]
You will need to merge the latest ngageoint:master into steph2a1:master and resolve the conflicts in whatever local editor you use for Git. Since your changes are very small, it will probably be easiest to just take the latest ngageoint:master and insert your new code back in.

**Pull request closed without merging**
