### PR TITLE
Issue 109 - add new example algorithms

### LINKED ISSUE #109: More algorithms
Add more algorithms to our test/example clusters.

### PR DESCRIPTION
**Pull request by tclarke**
closes #109 
Adds additional spectral and generic binary algorithms for testing.

### CODE REVIEW

**Comment by dfaller** [comment]
LGTM. I'm going to go ahead and merge this so we're good for tomorrow morning.

**Comment by dfaller** [comment]
Wait, why is this going into master? Trevor, can you change the PR to go into develop? If so, you can go ahead and merge it.

**Comment by tclarke** [comment]
Oops...selected the wrong branch. I'll fix and merge.

**Comment by tclarke** [comment]
Closing this request and opening a new one to develop.

**Pull request closed without merging**
