### PR TITLE
Issue 539 - Hide R&D job types

### PR DESCRIPTION
**Pull request by dickmancj-mil**
Added switch to Hide R&D job types to Job Types view.

image

### CODE REVIEW

**Comment by wardcr** [comment]
I added a new REST filter parameter "is_operational" to the /job-types and /job-types/status views that can be used to get only operational, only R&D job-types, or all job types.

**Comment by wardcr** [comment]
For the UI, I think it's more clear to invert the option to be something like "Show R&D" or "Include R&D".

**Comment by dickmancj-mil** [comment]
What should be the default value? Show or no?

**Comment by dfaller** [comment]
Let's go with show for right now.

**Pull request merged**
